### ISSUE TITLE
팀생성

### ISSUE THREAD

**Issue by KHsohee** [SungWoo824/kh2-final-circle#3]
안소희

**Comment by KHsohee** [comment]
팀생성  컨트롤러에서 도메인 주소를 어떻게 파라미터값으로 넣는지 모르겠음  postmapping에서 리다이렉트 주소를 바로 새로 생성된 도메인주소로 가게 해야 함

**Comment by KHsohee** [comment]
2020.01.30 팀생성 페이지 비동기 중복검사, 페이지 구현 완료, 등록기능(create)->DB까지 등록 완료 

남은일 : 버튼 비활성화

**Comment by KHsohee** [comment]
2020.01.31 팀생성 create 페이지 비동기  중복검사 , 등록버튼 비활성화 까지 모두 완료 
현재 하고 있는 일 : team/main페이지 생성 / 초대버튼 모달 화면 구현중

**Comment by KHsohee** [comment]
2020.02.05 팀멤버 초대 이메일보내기 완료 DB까지 확인은 했으나 
문제사항 : member테이블에 등록되어있는 이메일 주소로만 이메일이 전송된다 

해결해야할 문제 : db등록 상관없이 모든 사람들에게 이메일이 전송되어야 한다 

추후 계속 해야 할 일들 : 회원인지 비회원인지 식별하고 team_member db에 들어올 수 있기까지

**Comment by SungWoo824** [comment]
팀생성 기능 완료, 팀 기능 시작
